### ISSUE TITLE
Return ladders based on date/expiration  or historical based on ticker/exp/call/put

### ISSUE THREAD

**Issue by jmaslek** [Tyruiop/syncretism#35]
Currently, one needs the chain ID (i.e 'AAPL210730C00145000').  Would it be possible to either have an endpoint that returns all of those chain numbers based on the ticker, expiration and call/put, or be able to call historical based on those parameters.

**Comment by Tyruiop** [comment]
I implemented the following API call
`curl -X GET https://api.syncretism.io/ops/expirations/AAPL`

I think that combined with the `ladder` call (e.g. `curl -X GET https://api.syncretism.io/ops/ladder/PAYO/C/1626393600`) it should allow you to do what you want, waiting for your reply to close the issue :pray:

**Comment by jmaslek** [comment]
So having the expirations is awesome!  Is it possible to do something that could be like (that lists all possible contracts):

`curl -X GET https://api.syncretism.io/ops/contracts/{ticker}/{timestamp}` 

This would avoid having to loop through each expiration to get the ladder -> contractSymbol

**Comment by Tyruiop** [comment]
Isn't this equivalent to doing 
`curl -X GET https://api.syncretism.io/ops/ladder/PAYO/C/1626393600`
followed by `curl -X GET https://api.syncretism.io/ops/ladder/PAYO/P/1626393600`

the idea would be to do both in one request and to only return the contract symbols ?

**Comment by jmaslek** [comment]
Pretty much.   I am thinking the equivalent of the finance: `Ticker("AAPL").option_chains(date).calls["contractSymbol"]` merged with `Ticker("AAPL").option_chains(date).puts["contractSymbol"]` which returns the following:  
![Screen Shot 2021-07-29 at 3 55 22 PM](https://user-images.githubusercontent.com/18151143/127557479-d958eae4-3302-476e-a830-fb9896d31086.png)

I am not sure exactly how the API's are done, but I would imagine a json response like {'call': call_chain_ids , 'puts': call_chain_ids}.

That may not be super clear or not super helpful to have for you.

**Comment by Tyruiop** [comment]
Done! You can try `curl -X GET https://api.syncretism.io/ops/chain/PAYO/1626393600` to experiment with it, and thanks for the feature request!

**Comment by jmaslek** [comment]
Awesome thanks!  And what is the time stamp, I presume UNIX seconds?

**Comment by Tyruiop** [comment]
Yes, and even more specifically, it needs to be one of the timestamps provided by `curl -X GET https://api.syncretism.io/ops/expirations/PAYO`
