### ISSUE TITLE
Newer option chains not responding

### ISSUE THREAD

**Issue by jmaslek** [Tyruiop/syncretism#49]
Hey is this still crawling and updating?  We are no longer getting data from the historical endpoint:

https://github.com/OpenBB-finance/OpenBBTerminal/issues/1857

**Comment by Tyruiop** [comment]
Crawling is still happening and it works for me,
`curl -X GET https://api.syncretism.io/ops/historical/AAPL220715C00135000`

any particular option for which it is not working?

**Edit:** found a crontab that I accidentally forgot to update at some point, will process the missing data, that will take time though.

**Comment by jmaslek** [comment]
Thanks!
